import lexar.LexAnalyzer;
import lexar.Token;

import java.io.File;
import java.util.ArrayList;

public class Main {
    public static void main(String[] args) {
        File file = new File(args[0]); // for makefile

        LexAnalyzer lexicalAnalyzer = new LexAnalyzer(file);
        // Get the list of tokens generated by the lexical analyzer
        ArrayList<Token> tokenList = lexicalAnalyzer.getTokenList();
        // System.out.println("------------------Token List---------------------");
        // for (Token token : tokenList) {
        //     System.out.println(token);
        // }
    }
}